name: Release Every Other Monday
on:
  workflow_dispatch:
  schedule:
    - cron: '15 07,08,09 * * 2,3'
  # push:
  #   branches:
  #     - main
  

# Sets the GITHUB_TOKEN permissions to allow release
permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ssh-key: ${{ secrets.DEPLOY_KEY }}
      - name: git config
        run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
      - run: yarn
      - name: release
        id: release
        run: yarn release --ci
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Generate a token
        id: generate_token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PEM }}
          owner: ${{ github.repository_owner }}
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v3
        with:
          # To trigger the action from the same repo, cross-repo needs PAT 
          # To do this in organization level: https://github.com/peter-evans/repository-dispatch/issues/270
          token: ${{ steps.generate_token.outputs.token }}
          repository: hanbyul-here/release-trigger-test
          event-type: update-version
          client-payload: '{"ref": "${{ github.ref }}", "VERSION_NUMBER": "${{ env.VERSION_NUMBER }}"}'
