name: Release Every Other Monday

on:
  push:
    branches:
      - 'main'
  workflow_dispatch:

# Sets the GITHUB_TOKEN permissions to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  prep:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'yarn'
      - name: Install dependencies
        run: yarn
  release:
    runs-on: ubuntu-latest
    needs:
      - prep
    steps:
      - name: Release package
        run: yarn release --ci
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
