name: Release Every Other Monday
on:
  workflow_dispatch:
  schedule:
    - cron: '15 07,08,09 * * 2,3'
  # push:
  #   branches:
  #     - main
  

# Sets the GITHUB_TOKEN permissions to allow release
permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ssh-key: ${{ secrets.DEPLOY_KEY }}
      - name: git config
        run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
      - run: yarn
      - name: release
        id: release
        run: |
          echo "VERSION_NUMBER = yarn release --release-version" >> $GITHUB_OUTPUT
          yarn release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v3
        with:
          # To trigger the action from the same repo, cross-repo needs PAT 
          token: ${{ secrets.RELEASE_GH_TOKEN }}
          repository: hanbyul-here/release-trigger-test
          event-type: update-version
          client-payload: '{"version": "${{ steps.release.outputs.VERSION_NUMBER }}"}'