name: Release Every Other Monday

on:
  push:
    branches:
      - 'main'
  workflow_dispatch:

# Sets the GITHUB_TOKEN permissions to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  prep:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'yarn'
      - name: Install dependencies
        run: yarn
  weekindex:
    needs: prep
    runs-on: ubuntu-latest
    steps:
      - name: Check if this is an "every other Monday"
        run: |
          WEEK_NUM=$(date +%U)
          echo "weekindex=$((10#$WEEK_NUM % 2))" >> "$GITHUB_OUTPUT"
          echo "Current week number is: $WEEK_NUM"
  release:
    if: ${{ needs.weekindex.outputs.weekindex == 0 }}  
    runs-on: ubuntu-latest
    needs:
      - prep
      - weekindex
    steps:
      - name: Release package
        run: yarn release --ci
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
