name: Release Every Other Monday
on:
  schedule:
    - cron: '*/20 * * * *'
  # push:
  #   branches:
  #     - main
  # workflow_dispatch:

# Sets the GITHUB_TOKEN permissions to allow release
permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Check if this is an "every other Monday"
        id: check
        run: |
          # Check if the current week of the year is odd (every other Monday)
          WEEK_NUM=$(date +%U)
          if [ $(( WEEK_NUM % 2 )) -ne 1 ]; then
            echo "This is not an odd week, skipping release."
            exit 0
          fi
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: git config
        run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
      - run: yarn
      - run: yarn release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}