name: Release Every Other Monday


# Run the action every Monday at 10:00 AM UTC
# on:
#   schedule:
#     - cron: '0 10 * * 1'

on:
  pull_request:
    types: [opened, synchronize, reopened]
env:
  NODE: 20

jobs:
  weekindex:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: yarn install
      - name: Check if this is an "every other Monday"
        id: check
        run: |
          WEEK_NUM=$(date +%U)
          echo "weekindex=$((10#$WEEK_NUM % 2))" >> "$GITHUB_OUTPUT"
          echo "Current week number is: $WEEK_NUM"
  release:
    if: ${{ needs.weekindex.outputs.weekindex == 0 }}  
    runs-on: ubuntu-latest
    needs:
      - weekindex
    steps:
      - name: release package
        run: yarn release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
