name: Release Every Other Monday
on:
  push:
    branches:
      - main
  workflow_dispatch:

# Sets the GITHUB_TOKEN permissions to allow deployment to GitHub Pages
permissions:
  contents: write
  id-token: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: main
      - env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_GH_TOKEN }}
        uses: JoshuaKGoldberg/release-it-action@v0.2.2