name: Release Every Other Monday
on:
  workflow_dispatch:
  schedule:
    - cron: '15 07,08,09 * * 2,3'
  # push:
  #   branches:
  #     - main
  

# Sets the GITHUB_TOKEN permissions to allow release
permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ssh-key: ${{ secrets.DEPLOY_KEY }}
      - name: git config
        run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
      - run: yarn
      - run: yarn release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}